services:
  - type: worker
    name: tarjimon-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
      - key: GOOGLE_APPLICATION_CREDENTIALS_JSON
        sync: false
